<?
//A file full of functions used in team stats

//$team_avatars_dir = "/sharehome/htdocs/c/users/teams/avatar";
//$team_avatars_url = "/c/users/teams/avatar";
//
//$team_icons_dir   = "/sharehome/htdocs/c/users/teams/icon";
//$team_icons_url   = "/c/users/teams/icon";



// -----------------------------------------------------------------------------
//function url_for_team_stats($tid, $roundid = "") {
//    global $code_url;
//    return $roundid
//        ? "$code_url/stats/teams/tdetail.php?tid=$tid&amp;roundid=$roundid"
//        : "$code_url/stats/teams/tdetail.php?tid=$tid";
//}
//
//function link_to_team_stats($tid, $roundid, $prompt = "") {
//    if($prompt == "") {
//        $prompt = $roundid;
//    }
//    return link_to_url(url_for_team_stats($tid, $roundid), $prompt);
//}


